export { default as AppMain } from './AppMain.vue'
export { default as TheNavbar } from './TheNavbar.vue'
export { default as TheSidebar } from './TheSidebar.vue'
export { default as TheProfile } from '@/components/headers/TheProfile.vue'
export { default as TheShortCut } from '@/components/headers/TheShortCut.vue'
export { default as TheNotification } from '@/components/headers/TheNotification.vue'
export { default as TheLanguage } from '@/components/headers/TheLanguage.vue'
export { default as TheDardmode } from '@/components/DarkMode.vue'
